# Generated by Django 4.2 on 2023-04-28 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_task_datecompleted_propietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boveda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefonoAuxiliar',
            field=models.CharField(blank=True, default=111, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FamiliarDifunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresCompletos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('telefonoAuxiliar', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Difunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresCompletos', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateTimeField()),
                ('fechaDefuncion', models.DateTimeField()),
                ('fechaDejoEnBoveda', models.DateTimeField()),
                ('fechaFinAlquiler', models.DateTimeField(blank=True, null=True)),
                ('idBoveda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.boveda')),
                ('idFamiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.familiardifunto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='boveda',
            name='idPropietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.propietario'),
        ),
        migrations.AddField(
            model_name='boveda',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
